name: prosmart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.4
  intl: ^0.20.2
  firebase_storage: ^12.4.3
  universal_html: ^2.2.4
  qr_flutter: ^4.1.0
  file_picker: ^9.0.0
  firebase_auth: ^5.5.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
