// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCjt9wpNH7z1KGZyMHyy8wSpxhPv5ovCI',
    appId: '1:503392659179:web:68cf0745962b30ad5380ae',
    messagingSenderId: '503392659179',
    projectId: 'prosmartvs',
    authDomain: 'prosmartvs.firebaseapp.com',
    storageBucket: 'prosmartvs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wZkg0YKmT9GG22Jg91GcQchHBqbgjwk',
    appId: '1:503392659179:android:a21f70d9c434a5fc5380ae',
    messagingSenderId: '503392659179',
    projectId: 'prosmartvs',
    storageBucket: 'prosmartvs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv4i3MSk8gK4Hml9tgI4HfOl-7wQRxTXk',
    appId: '1:503392659179:ios:82d68c339fd3e37d5380ae',
    messagingSenderId: '503392659179',
    projectId: 'prosmartvs',
    storageBucket: 'prosmartvs.appspot.com',
    iosBundleId: 'com.example.prosmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwr1yIDnqldDTuUwH2WoOLozUzJlJyJg',
    appId: '1:1061544578569:ios:f21df7e32ec0628870f2d8',
    messagingSenderId: '1061544578569',
    projectId: 'app-prosmart',
    storageBucket: 'app-prosmart.firebasestorage.app',
    iosBundleId: 'com.example.prosmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-4tLHWPkQZOzukFc0QiOyVmhJ-Oy4AuQ',
    appId: '1:503392659179:web:8c3f75a2688a69ff5380ae',
    messagingSenderId: '503392659179',
    projectId: 'prosmartvs',
    authDomain: 'prosmartvs.firebaseapp.com',
    storageBucket: 'prosmartvs.appspot.com',
  );

}